[2023-07-03 19:39:38,316] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-07-02T00:00:00+00:00 [queued]>
[2023-07-03 19:39:38,362] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2023-07-02T00:00:00+00:00 [queued]>
[2023-07-03 19:39:38,364] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:39:38,365] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2023-07-03 19:39:38,366] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:39:38,391] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2023-07-02T00:00:00+00:00
[2023-07-03 19:39:38,397] {standard_task_runner.py:52} INFO - Started process 215 to run task
[2023-07-03 19:39:38,415] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2023-07-02T00:00:00+00:00', '--job-id', '47', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpox0hp_xm', '--error-file', '/tmp/tmpg7vydp8v']
[2023-07-03 19:39:38,417] {standard_task_runner.py:77} INFO - Job 47: Subtask task_zero
[2023-07-03 19:39:38,531] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2023-07-02T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-07-03 19:39:38,659] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2023-07-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-02T00:00:00+00:00
[2023-07-03 19:39:38,663] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-03 19:39:38,664] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2023-07-03 19:39:38,680] {subprocess.py:75} INFO - Output:
[2023-07-03 19:39:44,039] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-07-03 19:39:44,688] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.2)
[2023-07-03 19:39:44,718] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2023-07-03 19:40:14,026] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-03 19:40:14,107] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20230702T000000, start_date=20230703T193938, end_date=20230703T194014
[2023-07-03 19:40:14,150] {local_task_job.py:199} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-07-03 19:40:14,157] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 215
[2023-07-03 19:40:14,159] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-03 19:40:14,160] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2023-07-03 19:40:14,172] {process_utils.py:66} INFO - Process psutil.Process(pid=215, status='terminated', exitcode=1, started='19:39:38') (215) terminated with exit code 1
