[2023-07-03 19:40:16,083] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2023-07-02T00:00:00+00:00 [queued]>
[2023-07-03 19:40:16,125] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2023-07-02T00:00:00+00:00 [queued]>
[2023-07-03 19:40:16,127] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:40:16,128] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-03 19:40:16,128] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:40:16,153] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2023-07-02T00:00:00+00:00
[2023-07-03 19:40:16,158] {standard_task_runner.py:52} INFO - Started process 312 to run task
[2023-07-03 19:40:16,167] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_one', '2023-07-02T00:00:00+00:00', '--job-id', '48', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp5jcpa90w', '--error-file', '/tmp/tmpu5wjx6m0']
[2023-07-03 19:40:16,169] {standard_task_runner.py:77} INFO - Job 48: Subtask task_one
[2023-07-03 19:40:16,270] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_one 2023-07-02T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-07-03 19:40:16,409] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2023-07-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-02T00:00:00+00:00
[2023-07-03 19:40:17,487] {logging_mixin.py:104} INFO - wrote file: m1a.html
[2023-07-03 19:40:17,489] {logging_mixin.py:104} INFO - pulled: m1a.html
[2023-07-03 19:40:17,490] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:40:32,664] {logging_mixin.py:104} INFO - wrote file: m1b.html
[2023-07-03 19:40:32,666] {logging_mixin.py:104} INFO - pulled: m1b.html
[2023-07-03 19:40:32,666] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:40:47,898] {logging_mixin.py:104} INFO - wrote file: m1c.html
[2023-07-03 19:40:47,902] {logging_mixin.py:104} INFO - pulled: m1c.html
[2023-07-03 19:40:47,905] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:03,118] {logging_mixin.py:104} INFO - wrote file: m2a.html
[2023-07-03 19:41:03,120] {logging_mixin.py:104} INFO - pulled: m2a.html
[2023-07-03 19:41:03,121] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:18,566] {logging_mixin.py:104} INFO - wrote file: m2b.html
[2023-07-03 19:41:18,569] {logging_mixin.py:104} INFO - pulled: m2b.html
[2023-07-03 19:41:18,571] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:33,975] {logging_mixin.py:104} INFO - wrote file: m2c.html
[2023-07-03 19:41:33,977] {logging_mixin.py:104} INFO - pulled: m2c.html
[2023-07-03 19:41:33,978] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:49,197] {logging_mixin.py:104} INFO - wrote file: m3b.html
[2023-07-03 19:41:49,200] {logging_mixin.py:104} INFO - pulled: m3b.html
[2023-07-03 19:41:49,202] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:42:04,562] {logging_mixin.py:104} INFO - wrote file: m4a.html
[2023-07-03 19:42:04,564] {logging_mixin.py:104} INFO - pulled: m4a.html
[2023-07-03 19:42:04,566] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:42:06,134] {local_task_job.py:76} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-03 19:42:06,170] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 312
[2023-07-03 19:42:06,190] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-03 19:42:06,275] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 88, in catalog
    time.sleep(15)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-03 19:42:06,382] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=assignment, task_id=task_one, execution_date=20230702T000000, start_date=20230703T194016, end_date=20230703T194206
[2023-07-03 19:42:06,764] {process_utils.py:66} INFO - Process psutil.Process(pid=312, status='terminated', exitcode=1, started='19:40:15') (312) terminated with exit code 1
