[2023-07-03 19:40:16,152] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2023-06-26T00:00:00+00:00 [queued]>
[2023-07-03 19:40:16,194] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_one 2023-06-26T00:00:00+00:00 [queued]>
[2023-07-03 19:40:16,196] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:40:16,197] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-03 19:40:16,197] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-03 19:40:16,221] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): task_one> on 2023-06-26T00:00:00+00:00
[2023-07-03 19:40:16,227] {standard_task_runner.py:52} INFO - Started process 314 to run task
[2023-07-03 19:40:16,239] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_one', '2023-06-26T00:00:00+00:00', '--job-id', '49', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpg2c7ke64', '--error-file', '/tmp/tmphxdzkbbp']
[2023-07-03 19:40:16,241] {standard_task_runner.py:77} INFO - Job 49: Subtask task_one
[2023-07-03 19:40:16,349] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_one 2023-06-26T00:00:00+00:00 [running]> on host 7f7a4865b07a
[2023-07-03 19:40:16,485] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_one
AIRFLOW_CTX_EXECUTION_DATE=2023-06-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-26T00:00:00+00:00
[2023-07-03 19:40:16,878] {logging_mixin.py:104} INFO - wrote file: m1a.html
[2023-07-03 19:40:16,879] {logging_mixin.py:104} INFO - pulled: m1a.html
[2023-07-03 19:40:16,880] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:40:32,130] {logging_mixin.py:104} INFO - wrote file: m1b.html
[2023-07-03 19:40:32,131] {logging_mixin.py:104} INFO - pulled: m1b.html
[2023-07-03 19:40:32,132] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:40:47,602] {logging_mixin.py:104} INFO - wrote file: m1c.html
[2023-07-03 19:40:47,607] {logging_mixin.py:104} INFO - pulled: m1c.html
[2023-07-03 19:40:47,608] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:02,846] {logging_mixin.py:104} INFO - wrote file: m2a.html
[2023-07-03 19:41:02,848] {logging_mixin.py:104} INFO - pulled: m2a.html
[2023-07-03 19:41:02,849] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:18,100] {logging_mixin.py:104} INFO - wrote file: m2b.html
[2023-07-03 19:41:18,103] {logging_mixin.py:104} INFO - pulled: m2b.html
[2023-07-03 19:41:18,104] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:33,522] {logging_mixin.py:104} INFO - wrote file: m2c.html
[2023-07-03 19:41:33,525] {logging_mixin.py:104} INFO - pulled: m2c.html
[2023-07-03 19:41:33,525] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:41:48,897] {logging_mixin.py:104} INFO - wrote file: m3b.html
[2023-07-03 19:41:48,900] {logging_mixin.py:104} INFO - pulled: m3b.html
[2023-07-03 19:41:48,901] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:42:04,275] {logging_mixin.py:104} INFO - wrote file: m4a.html
[2023-07-03 19:42:04,278] {logging_mixin.py:104} INFO - pulled: m4a.html
[2023-07-03 19:42:04,278] {logging_mixin.py:104} INFO - --- waiting ---
[2023-07-03 19:42:06,135] {local_task_job.py:76} ERROR - Received SIGTERM. Terminating subprocesses
[2023-07-03 19:42:06,185] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 314
[2023-07-03 19:42:06,194] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-07-03 19:42:06,264] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/assignment.py", line 88, in catalog
    time.sleep(15)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-07-03 19:42:06,429] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=assignment, task_id=task_one, execution_date=20230626T000000, start_date=20230703T194016, end_date=20230703T194206
[2023-07-03 19:42:06,846] {process_utils.py:66} INFO - Process psutil.Process(pid=314, status='terminated', exitcode=1, started='19:40:15') (314) terminated with exit code 1
